### ISSUE TITLE
qpUpdate feature request

### ISSUE THREAD

**Issue by denispelli** [BrainardLab/mQUESTPlus#11]
Dear David
it's possible that i'm naively misusing things. I'm using QuestPlus to make a maximum likelihood fit to old data. We use qpUpdate to stuff our trial data, trial by trial, into the questData.trialData struct. Then we call qpFit to get the answer. It works fine, but it's very slow. Running the MATLAB profiler tells me that most of the time is spent computing entropies in qpUpdateExpectedNextEnropiesByStim and qpArrayEntropy. I don't need entropies, so I made my own version of qpUpdate with those two calls commented out. It works fine, and fast.

My request is that you offer us a flag that we can pass to qpUpdate, e.g. 'noEntropies' that tells it to skip the entropy calculations.

What do you think?
best
Denis

**Comment by DavidBrainard** [comment]
I can do this easily and also tweak the documentation as per the next issue.  
Will take care of it when I get a moment.

**Comment by denispelli** [comment]
yay. thx.


[image: photo]
*Denis Pelli*
Professor of Psychology & Neural Science, New York University
+1-646-258-7524 | denis.pelli@nyu.edu | http://psych.nyu.edu/pelli/ | Skype:
denispelli <#> | http://denispelli.com
<http://www.facebook.com/denispelli>
<http://www.linkedin.com/in/denispelli/> <http://twitter.com/denispelli>

**Comment by DavidBrainard** [comment]
OK.  I added a key/value pair that may be passed to qpInitialize.  The key is 'noentropy' and if you set it to true it should skip the entropy calculations on initialize and on update.

I verified that this change didn't break any of the existing tests, but have not tested what happens when it is set to true.  

Can you test and let me know if it works for you?  The entropy initialization that is usually done by qpInitialize is skipped, and then the entropy update is also skipped in qpUpdate.

If it works, we're good.  If not, maybe email me a short test program.
